trigger: 
- main

stages: 
- stage: Build
  jobs:
  - job: Build
    pool:
        vmimage: ubuntu-latest
    steps:
    - task: Npm@1
      inputs:
        command: 'install'

    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
        vmimage: ubuntu-latest
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
        
    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Add your Azure subs'
        appType: 'webAppLinux'
        WebAppName: 'Add Azure Web App Name'
        packageForLinux: '$(System.ArtifactsDirectory)/drop'
        RuntimeStack: 'NODE|22-lts'
        StartupCommand: 'pm2 serve /home/site/wwwroot --no-daemon --spa'
        DeploymentTypeLinux: 'oneDeploy'
